### ISSUE TITLE
Android Gradle plugin 2.2.1 breaks build with gnustl_shared

### ISSUE THREAD

**Issue by oysteinmyrmo** [android-ndk/ndk#217]
We have a build with our own C++ code. After updating to `com.android.tools.build:gradle:2.2.1` in the project `build.gradle` the build breaks (see Gradle error report at the bottom). The build using gnustl_shared is currently done in this order:

A. myNativeModule: Build native libraries (our own C++ code). This is where the error originates from. The externalNativeBuild part in build.gradle is

```
externalNativeBuild {
    cmake {
        cppFlags    "-fexceptions", "-frtti", "-Wno-error"
        arguments   "-DANDROID_STL=${STL_VERSION}"
        abiFilters  "armeabi-v7a"
    }
}
```

where "${STL_VERSION}" is gnustl_static by default and gnustl_shared for the build in question.

B. myLibraryModule: Copy the desired shared objects into `src/main/jniLibs` after myNativeModule is built. If we are using gnustl_shared, copy it from the NDK directory, then create aar package.

It seems like the new version of the plugin is looking for libgnustl_shared.so in the obj directory, which is weird.

What can I be missing here? Is this expected behavior?

**Full Gradle error report:**

```
[Gradle failure report] 11:56:55.510 [ERROR] [org.gradle.BuildExceptionReporter] 
[11:57:09][Gradle failure report] 11:56:55.511 [ERROR] [org.gradle.BuildExceptionReporter] FAILURE: Build failed with an exception.
[11:57:09][Gradle failure report] 11:56:55.511 [ERROR] [org.gradle.BuildExceptionReporter] 
[11:57:09][Gradle failure report] 11:56:55.511 [ERROR] [org.gradle.BuildExceptionReporter] * What went wrong:
[11:57:09][Gradle failure report] 11:56:55.511 [ERROR] [org.gradle.BuildExceptionReporter] Execution failed for task ':myNativeModule:externalNativeBuildRelease'.
[11:57:09][Gradle failure report] 11:56:55.511 [ERROR] [org.gradle.BuildExceptionReporter] > java.io.FileNotFoundException: /path/to/my/project/myNativeModule/build/intermediates/cmake/release/obj/armeabi-v7a/libgnustl_shared.so (No such file or directory)
[11:57:09][Gradle failure report] 11:56:55.511 [ERROR] [org.gradle.BuildExceptionReporter] 
[11:57:09][Gradle failure report] 11:56:55.511 [ERROR] [org.gradle.BuildExceptionReporter] * Exception is:
[11:57:09][Gradle failure report] 11:56:55.512 [ERROR] [org.gradle.BuildExceptionReporter] org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':myNativeModule:externalNativeBuildRelease'.
[11:57:09][Gradle failure report] 11:56:55.512 [ERROR] [org.gradle.BuildExceptionReporter]  at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
[11:57:09][Gradle failure report] 11:56:55.512 [ERROR] [org.gradle.BuildExceptionReporter]  at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
[11:57:09][Gradle failure report] 11:56:55.512 [ERROR] [org.gradle.BuildExceptionReporter]  at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
[11:57:09][Gradle failure report] 11:56:55.512 [ERROR] [org.gradle.BuildExceptionReporter]  at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:66)
[11:57:09][Gradle failure report] 11:56:55.512 [ERROR] [org.gradle.BuildExceptionReporter]  at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
[11:57:09][Gradle failure report] 11:56:55.512 [ERROR] [org.gradle.BuildExceptionReporter]  at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:52)
[11:57:09][Gradle failure report] 11:56:55.512 [ERROR] [org.gradle.BuildExceptionReporter]  at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
[11:57:09][Gradle failure report] 11:56:55.512 [ERROR] [org.gradle.BuildExceptionReporter]  at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
[11:57:09][Gradle failure report] 11:56:55.512 [ERROR] [org.gradle.BuildExceptionReporter]  at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
[11:57:09][Gradle failure report] 11:56:55.512 [ERROR] [org.gradle.BuildExceptionReporter]  at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:203)
[11:57:09][Gradle failure report] 11:56:55.512 [ERROR] [org.gradle.BuildExceptionReporter]  at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:185)
[11:57:09][Gradle failure report] 11:56:55.512 [ERROR] [org.gradle.BuildExceptionReporter]  at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:66)
[11:57:09][Gradle failure report] 11:56:55.512 [ERROR] [org.gradle.BuildExceptionReporter]  at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:50)
[11:57:09][Gradle failure report] 11:56:55.512 [ERROR] [org.gradle.BuildExceptionReporter]  at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor.process(DefaultTaskPlanExecutor.java:25)
[11:57:09][Gradle failure report] 11:56:55.512 [ERROR] [org.gradle.BuildExceptionReporter]  at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(DefaultTaskGraphExecuter.java:110)
[11:57:09][Gradle failure report] 11:56:55.512 [ERROR] [org.gradle.BuildExceptionReporter]  at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:37)
[11:57:09][Gradle failure report] 11:56:55.512 [ERROR] [org.gradle.BuildExceptionReporter]  at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
[11:57:09][Gradle failure report] 11:56:55.512 [ERROR] [org.gradle.BuildExceptionReporter]  at org.gradle.execution.DefaultBuildExecuter.access$000(DefaultBuildExecuter.java:23)
[11:57:09][Gradle failure report] 11:56:55.512 [ERROR] [org.gradle.BuildExceptionReporter]  at org.gradle.execution.DefaultBuildExecuter$1.proceed(DefaultBuildExecuter.java:43)
[11:57:09][Gradle failure report] 11:56:55.512 [ERROR] [org.gradle.BuildExceptionReporter]  at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:32)
[11:57:09][Gradle failure report] 11:56:55.512 [ERROR] [org.gradle.BuildExceptionReporter]  at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
[11:57:09][Gradle failure report] 11:56:55.512 [ERROR] [org.gradle.BuildExceptionReporter]  at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:30)
[11:57:09][Gradle failure report] 11:56:55.512 [ERROR] [org.gradle.BuildExceptionReporter]  at org.gradle.initialization.DefaultGradleLauncher$4.run(DefaultGradleLauncher.java:153)
[11:57:09][Gradle failure report] 11:56:55.512 [ERROR] [org.gradle.BuildExceptionReporter]  at org.gradle.internal.Factories$1.create(Factories.java:22)
[11:57:09][Gradle failure report] 11:56:55.512 [ERROR] [org.gradle.BuildExceptionReporter]  at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:91)
[11:57:09][Gradle failure report] 11:56:55.512 [ERROR] [org.gradle.BuildExceptionReporter]  at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:53)
[11:57:09][Gradle failure report] 11:56:55.512 [ERROR] [org.gradle.BuildExceptionReporter]  at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:150)
[11:57:09][Gradle failure report] 11:56:55.512 [ERROR] [org.gradle.BuildExceptionReporter]  at org.gradle.initialization.DefaultGradleLauncher.access$200(DefaultGradleLauncher.java:32)
[11:57:09][Gradle failure report] 11:56:55.513 [ERROR] [org.gradle.BuildExceptionReporter]  at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:98)
[11:57:09][Gradle failure report] 11:56:55.513 [ERROR] [org.gradle.BuildExceptionReporter]  at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:92)
[11:57:09][Gradle failure report] 11:56:55.513 [ERROR] [org.gradle.BuildExceptionReporter]  at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:91)
[11:57:09][Gradle failure report] 11:56:55.513 [ERROR] [org.gradle.BuildExceptionReporter]  at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:63)
[11:57:09][Gradle failure report] 11:56:55.513 [ERROR] [org.gradle.BuildExceptionReporter]  at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:92)
[11:57:09][Gradle failure report] 11:56:55.513 [ERROR] [org.gradle.BuildExceptionReporter]  at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:83)
[11:57:09][Gradle failure report] 11:56:55.513 [ERROR] [org.gradle.BuildExceptionReporter]  at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:99)
[11:57:09][Gradle failure report] 11:56:55.513 [ERROR] [org.gradle.BuildExceptionReporter]  at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:28)
[11:57:09][Gradle failure report] 11:56:55.513 [ERROR] [org.gradle.BuildExceptionReporter]  at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
[11:57:09][Gradle failure report] 11:56:55.513 [ERROR] [org.gradle.BuildExceptionReporter]  at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:48)
[11:57:09][Gradle failure report] 11:56:55.513 [ERROR] [org.gradle.BuildExceptionReporter]  at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:30)
[11:57:09][Gradle failure report] 11:56:55.513 [ERROR] [org.gradle.BuildExceptionReporter]  at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:81)
[11:57:09][Gradle failure report] 11:56:55.513 [ERROR] [org.gradle.BuildExceptionReporter]  at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:46)
[11:57:09][Gradle failure report] 11:56:55.513 [ERROR] [org.gradle.BuildExceptionReporter]  at org.gradle.launcher.exec.DaemonUsageSuggestingBuildActionExecuter.execute(DaemonUsageSuggestingBuildActionExecuter.java:51)
[11:57:09][Gradle failure report] 11:56:55.513 [ERROR] [org.gradle.BuildExceptionReporter]  at org.gradle.launcher.exec.DaemonUsageSuggestingBuildActionExecuter.execute(DaemonUsageSuggestingBuildActionExecuter.java:28)
[11:57:09][Gradle failure report] 11:56:55.513 [ERROR] [org.gradle.BuildExceptionReporter]  at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:43)
[11:57:09][Gradle failure report] 11:56:55.513 [ERROR] [org.gradle.BuildExceptionReporter]  at org.gradle.internal.Actions$RunnableActionAdapter.execute(Actions.java:173)
[11:57:09][Gradle failure report] 11:56:55.513 [ERROR] [org.gradle.BuildExceptionReporter]  at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:239)
[11:57:09][Gradle failure report] 11:56:55.513 [ERROR] [org.gradle.BuildExceptionReporter]  at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:212)
[11:57:09][Gradle failure report] 11:56:55.513 [ERROR] [org.gradle.BuildExceptionReporter]  at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:35)
[11:57:09][Gradle failure report] 11:56:55.513 [ERROR] [org.gradle.BuildExceptionReporter]  at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:24)
[11:57:09][Gradle failure report] 11:56:55.513 [ERROR] [org.gradle.BuildExceptionReporter]  at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:33)
[11:57:09][Gradle failure report] 11:56:55.513 [ERROR] [org.gradle.BuildExceptionReporter]  at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:22)
[11:57:09][Gradle failure report] 11:56:55.513 [ERROR] [org.gradle.BuildExceptionReporter]  at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:205)
[11:57:09][Gradle failure report] 11:56:55.513 [ERROR] [org.gradle.BuildExceptionReporter]  at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:169)
[11:57:09][Gradle failure report] 11:56:55.513 [ERROR] [org.gradle.BuildExceptionReporter]  at org.gradle.launcher.Main.doAction(Main.java:33)
[11:57:09][Gradle failure report] 11:56:55.513 [ERROR] [org.gradle.BuildExceptionReporter]  at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
[11:57:09][Gradle failure report] 11:56:55.513 [ERROR] [org.gradle.BuildExceptionReporter]  at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:55)
[11:57:09][Gradle failure report] 11:56:55.513 [ERROR] [org.gradle.BuildExceptionReporter]  at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:36)
[11:57:09][Gradle failure report] 11:56:55.513 [ERROR] [org.gradle.BuildExceptionReporter]  at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
[11:57:09][Gradle failure report] 11:56:55.513 [ERROR] [org.gradle.BuildExceptionReporter]  at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:30)
[11:57:09][Gradle failure report] 11:56:55.513 [ERROR] [org.gradle.BuildExceptionReporter]  at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:129)
[11:57:09][Gradle failure report] 11:56:55.513 [ERROR] [org.gradle.BuildExceptionReporter]  at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
[11:57:09][Gradle failure report] 11:56:55.514 [ERROR] [org.gradle.BuildExceptionReporter] Caused by: org.gradle.api.UncheckedIOException: java.io.FileNotFoundException: /path/to/my/project/myNativeModule/build/intermediates/cmake/release/obj/armeabi-v7a/libgnustl_shared.so (No such file or directory)
[11:57:09][Gradle failure report] 11:56:55.514 [ERROR] [org.gradle.BuildExceptionReporter]  at org.gradle.internal.UncheckedException.throwAsUncheckedException(UncheckedException.java:43)
[11:57:09][Gradle failure report] 11:56:55.514 [ERROR] [org.gradle.BuildExceptionReporter]  at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:78)
[11:57:09][Gradle failure report] 11:56:55.514 [ERROR] [org.gradle.BuildExceptionReporter]  at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.doExecute(AnnotationProcessingTaskFactory.java:228)
[11:57:09][Gradle failure report] 11:56:55.514 [ERROR] [org.gradle.BuildExceptionReporter]  at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:221)
[11:57:09][Gradle failure report] 11:56:55.514 [ERROR] [org.gradle.BuildExceptionReporter]  at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:210)
[11:57:09][Gradle failure report] 11:56:55.514 [ERROR] [org.gradle.BuildExceptionReporter]  at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:621)
[11:57:09][Gradle failure report] 11:56:55.514 [ERROR] [org.gradle.BuildExceptionReporter]  at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:604)
[11:57:09][Gradle failure report] 11:56:55.514 [ERROR] [org.gradle.BuildExceptionReporter]  at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
[11:57:09][Gradle failure report] 11:56:55.514 [ERROR] [org.gradle.BuildExceptionReporter]  at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
[11:57:09][Gradle failure report] 11:56:55.514 [ERROR] [org.gradle.BuildExceptionReporter]  ... 60 more
[11:57:09][Gradle failure report] 11:56:55.514 [ERROR] [org.gradle.BuildExceptionReporter] Caused by: java.io.FileNotFoundException: /path/to/my/project/myNativeModule/build/intermediates/cmake/release/obj/armeabi-v7a/libgnustl_shared.so (No such file or directory)
[11:57:09][Gradle failure report] 11:56:55.514 [ERROR] [org.gradle.BuildExceptionReporter]  at com.google.common.io.Files$FileByteSink.openStream(Files.java:200)
[11:57:09][Gradle failure report] 11:56:55.514 [ERROR] [org.gradle.BuildExceptionReporter]  at com.google.common.io.Files$FileByteSink.openStream(Files.java:188)
[11:57:09][Gradle failure report] 11:56:55.514 [ERROR] [org.gradle.BuildExceptionReporter]  at com.google.common.io.ByteSource.copyTo(ByteSource.java:240)
[11:57:09][Gradle failure report] 11:56:55.514 [ERROR] [org.gradle.BuildExceptionReporter]  at com.google.common.io.Files.copy(Files.java:305)
[11:57:09][Gradle failure report] 11:56:55.514 [ERROR] [org.gradle.BuildExceptionReporter]  at com.android.build.gradle.tasks.ExternalNativeBuildTask.build(ExternalNativeBuildTask.java:201)
[11:57:09][Gradle failure report] 11:56:55.514 [ERROR] [org.gradle.BuildExceptionReporter]  at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:75)
[11:57:09][Gradle failure report] 11:56:55.514 [ERROR] [org.gradle.BuildExceptionReporter]  ... 67 more
[11:57:09][Gradle failure report] 11:56:55.514 [ERROR] [org.gradle.BuildExceptionReporter] 
```

**Comment by DanAlbert** [comment]
I'm guessing this is related to the fix for https://code.google.com/p/android/issues/detail?id=214664. Checking with the gradle folks before I close this.

**Comment by jomof** [comment]
Gradle folk here,
I fiddled around with reproducing this and wasn't able to so I think I'm missing something. Could you provide exact repro steps? I'm not sure what is happening during (B).

**Comment by oysteinmyrmo** [comment]
It seems the step B above is not needed to trigger the error, only A which is a cmake build using com.android.library.

I have tried reproducing the issue in a minimum sample and in other smaller cmake builds we have, but I am not able to. So there is an issue in the build I am referring to, but I cannot figure out where. If we are able  to find the culprit I will post it here, but for now we'll just stick to 2.2.0 for that particular build. (I am unfortunately not able to post the entire build since it is internal to my company.)

**Comment by jomof** [comment]
I understand about the full build. One thing I noticed about the callstack you posted is this path in the exception:

/path/to/my/project/myNativeModule/build/intermediates/cmake/release/obj/armeabi-v7a/libgnustl_shared.so 

That /path/to/my/project part seems fabricated. Did you search/replace in the exception before you posted or is this literally the exception that was produced by gradle plugin?

**Comment by oysteinmyrmo** [comment]
Yes, the `/path/to/my/project` is searched and replaced by me (just because our product name was in the path). The path given in the stack trace is correct.

**Comment by oysteinmyrmo** [comment]
We are still having this issue, for all plugin versions after 2.2.0 (i.e. 2.2.1, 2.2.2 and 2.2.3). They all give the error as depicted above. We have not been able to figure out which part of the build that triggers the error, other than that it happens _after_ the actual native build. That is, the C++ code is compiled and seemingly straight after this happens.

Is the plugin code available anywhere? The error is reported to be at `ExternalNativeBuildTask.java:201`. Maybe I can track some error down if I can view the changelist between 2.2.0 and 2.2.1 for that particular code. Perhaps the plugin was changed to try to copy libgnustl_shared.so if `"-DANDROID_STL=gnustl_shared"` was provided?

**Comment by jomof** [comment]
The change that added the STL copying is here: https://android.googlesource.com/platform/tools/base/+/studio-master-dev%5E!/

Yes, we do check that the -DANDROID_STL is set and copy based on that. You can find that change here (search for getStlSharedObjectFiles)
https://android.googlesource.com/platform/tools/base/+/studio-2.2.2%5E1..studio-2.2.2/

The build directory is not Java-only. 

I can't understand why the obj/ folder doesn't exist for you. Any chance your build.gradle is manipulating output\intermediate folders?

**Comment by oysteinmyrmo** [comment]
Right, so our error was setting the output directories like this:

```
SET_TARGET_PROPERTIES(myLib PROPERTIES LIBRARY_OUTPUT_DIRECTORY someDir)
SET_TARGET_PROPERTIES(myLib PROPERTIES LIBRARY_OUTPUT_DIRECTORY_RELEASE someDir)
SET_TARGET_PROPERTIES(myLib PROPERTIES LIBRARY_OUTPUT_DIRECTORY_DEBUG someDir)
```

I guess this is now done for us by the Gradle plugin behind the scene, so doing this ruins the build process. We did it some time back in the early days of Cmake with Gradle to make it build properly. Similar code is floating around the web so hopefully anyone else doing this might stumble upon it here.

Thanks a lot for helping in the right direction!
