### ISSUE TITLE
"_ZNSt8ios_base4InitC1Ev" not found in libc++_shared.so

### ISSUE THREAD

**Issue by rcdailey** [android-ndk/ndk#455]
#### Description

From Java, I load `libc++_shared.so` which I copied from:

    E:\android\android-ndk-r15b\sources\cxx-stl\llvm-libc++\libs\armeabi-v7a

However, once I load my own *.so which depends on STL, I get the following:

```
07-14 15:40:41.362  4815  4815 D ZActivity: Activity onCreate
07-14 15:40:41.362  4815  4815 D TTMApplication: Loading library: c++_shared
07-14 15:40:41.362  4815  4815 D dalvikvm: Trying to load lib /data/app-lib/com.ttm.zapp-1/libc++_shared.so 0x4114ba90
07-14 15:40:41.367  4815  4815 D dalvikvm: Added shared lib /data/app-lib/com.ttm.zapp-1/libc++_shared.so 0x4114ba90
07-14 15:40:41.367  4815  4815 D dalvikvm: No JNI_OnLoad found in /data/app-lib/com.ttm.zapp-1/libc++_shared.so 0x4114ba90, skipping init
07-14 15:40:41.367  4815  4815 D TTMApplication: Loading library: z
07-14 15:40:41.367  4815  4815 D dalvikvm: Trying to load lib /data/app-lib/com.ttm.zapp-1/libz.so 0x4114ba90
07-14 15:40:41.367  4815  4815 D dalvikvm: Added shared lib /data/app-lib/com.ttm.zapp-1/libz.so 0x4114ba90
07-14 15:40:41.367  4815  4815 D dalvikvm: No JNI_OnLoad found in /data/app-lib/com.ttm.zapp-1/libz.so 0x4114ba90, skipping init
07-14 15:40:41.367  4815  4815 D TTMApplication: Loading library: MagickCore-7
07-14 15:40:41.367  4815  4815 D dalvikvm: Trying to load lib /data/app-lib/com.ttm.zapp-1/libMagickCore-7.so 0x4114ba90
07-14 15:40:41.372  4815  4815 D dalvikvm: Added shared lib /data/app-lib/com.ttm.zapp-1/libMagickCore-7.so 0x4114ba90
07-14 15:40:41.372  4815  4815 D dalvikvm: No JNI_OnLoad found in /data/app-lib/com.ttm.zapp-1/libMagickCore-7.so 0x4114ba90, skipping init
07-14 15:40:41.372  4815  4815 D TTMApplication: Loading library: MagickWand-7
07-14 15:40:41.372  4815  4815 D dalvikvm: Trying to load lib /data/app-lib/com.ttm.zapp-1/libMagickWand-7.so 0x4114ba90
07-14 15:40:41.372  4815  4815 D dalvikvm: Added shared lib /data/app-lib/com.ttm.zapp-1/libMagickWand-7.so 0x4114ba90
07-14 15:40:41.372  4815  4815 D dalvikvm: No JNI_OnLoad found in /data/app-lib/com.ttm.zapp-1/libMagickWand-7.so 0x4114ba90, skipping init
07-14 15:40:41.372  4815  4815 D TTMApplication: Loading library: zApp
07-14 15:40:41.372  4815  4815 D dalvikvm: Trying to load lib /data/app-lib/com.ttm.zapp-1/libzApp.so 0x4114ba90
07-14 15:40:41.412  4815  4815 E dalvikvm: dlopen("/data/app-lib/com.ttm.zapp-1/libzApp.so") failed: Cannot load library: soinfo_relocate(linker.cpp:975): cannot locate symbol "_ZNSt8ios_base4InitC1Ev" referenced by "libzApp.so"...
07-14 15:40:41.412  4815  4815 D AndroidRuntime: Shutting down VM
07-14 15:40:41.412  4815  4815 W dalvikvm: threadid=1: thread exiting with uncaught exception (group=0x40c45930)
07-14 15:40:41.417  4815  4815 E AndroidRuntime: FATAL EXCEPTION: main
07-14 15:40:41.417  4815  4815 E AndroidRuntime: java.lang.UnsatisfiedLinkError: Cannot load library: soinfo_relocate(linker.cpp:975): cannot locate symbol "_ZNSt8ios_base4InitC1Ev" referenced by "libzApp.so"...
07-14 15:40:41.417  4815  4815 E AndroidRuntime:        at java.lang.Runtime.loadLibrary(Runtime.java:371)
07-14 15:40:41.417  4815  4815 E AndroidRuntime:        at java.lang.System.loadLibrary(System.java:535)
07-14 15:40:41.417  4815  4815 E AndroidRuntime:        at com.ttm.UI.utils.LibraryLoader.LoadSingleLibrary(LibraryLoader.java:30)
07-14 15:40:41.417  4815  4815 E AndroidRuntime:        at com.ttm.UI.utils.LibraryLoader.LoadLibraries(LibraryLoader.java:49)
07-14 15:40:41.417  4815  4815 E AndroidRuntime:        at com.ttm.zapp.ZActivity.onCreate(ZActivity.java:18)
07-14 15:40:41.417  4815  4815 E AndroidRuntime:        at android.app.Activity.performCreate(Activity.java:5107)
07-14 15:40:41.417  4815  4815 E AndroidRuntime:        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1080)
07-14 15:40:41.417  4815  4815 E AndroidRuntime:        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2144)
07-14 15:40:41.417  4815  4815 E AndroidRuntime:        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2230)
07-14 15:40:41.417  4815  4815 E AndroidRuntime:        at android.app.ActivityThread.access$600(ActivityThread.java:141)
07-14 15:40:41.417  4815  4815 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1234)
07-14 15:40:41.417  4815  4815 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:99)
07-14 15:40:41.417  4815  4815 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:137)
07-14 15:40:41.417  4815  4815 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:5041)
07-14 15:40:41.417  4815  4815 E AndroidRuntime:        at java.lang.reflect.Method.invokeNative(Native Method)
07-14 15:40:41.417  4815  4815 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Method.java:511)
07-14 15:40:41.417  4815  4815 E AndroidRuntime:        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
07-14 15:40:41.417  4815  4815 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
07-14 15:40:41.417  4815  4815 E AndroidRuntime:        at dalvik.system.NativeStart.main(Native Method)
```

I can't determine if this is my code or a bug in the NDK.

#### Environment Details

* NDK Version: r15b official release
* Build sytem: CMake 3.9.0
* Host OS: Windows 10
* Compiler: clang
* ABI: armeabi-v7a
* STL: c++_shared
* NDK API level: android-15
* Device API level: 17 (Jellybean)

**Comment by rcdailey** [comment]
I had a third party library still compiled with gnu stl causing an abi compatibility issue. I found which static library was causing this by doing a grep on binary files for "ios_base". I rebuilt the library and this issue went away.
