### ISSUE TITLE
error after record

### ISSUE THREAD

**Issue by brok85** [android-ndk/ndk#492]
#### Description
I execute **python app_profiler.py** and the  **perf.data** file seems to be copied correctly on the host machine. However, before the app_profiler.py finish executing, I always get the following error:

DEBUG:root:run adb cmd: ['adb', 'pull', '/data/local/tmp/perf.data', 'perf.data']  [result True]
Traceback (most recent call last):

  File "app_profiler.py", line 335, in <module>
    profiler.profile()

  File "app_profiler.py", line 75, in profile
    self.collect_profiling_data()

  File "app_profiler.py", line 308, in collect_profiling_data
    binary_cache_builder.build_binary_cache()

  File "path-to-ndk-bundle/simpleperf/binary_cache_builder.py", line 62, in build_binary_cache
    self._pull_binaries_from_device()

  File "path-to-ndk-bundle/simpleperf/binary_cache_builder.py", line 154, in _pull_binaries_from_device
    self._check_and_pull_binary(binary, build_id, binary_cache_file)

  File "path-to-ndk-bundle/simpleperf/binary_cache_builder.py", line 165, in _check_and_pull_binary
    build_id = self._read_build_id(binary_cache_file)

  File "path-to-ndk-bundle/simpleperf/binary_cache_builder.py", line 184, in _read_build_id
    output = subprocess.check_output([self.readelf_path, '-n', file])

  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 566, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)

  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 710, in __init__errread, errwrite)

  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

What should I do?

Thanks for any help.

**UPDATE**: I tried to restore the whole ndk-bundle folder to the original files. Then I executed again the app_profiler.py with the same configuration and the execution finished correctly without errors. However, when I run the app_profiler.py again I got back the same error.

**UPDATE 2**: It seems that deleting the **binary_cache** folder before executing app_profiler.py again solves the problem. Now if I delete that folder I do not get the above error again. This should narrow the problem down.
#### Environment Details

* NDK Version: r15c.
* Host OS: Mac

**Comment by yabinc** [comment]
In r15c, app_profiler.py tries to pull native libs to binary_cache on host. If there are already files in binary_cache, it uses readelf to read build ids of the files to decide whether it needs to pull native libs again. You can fix the error by setting the line of readelf_path in app_profiler.config:
readelf_path = "../toolchains/aarch64-linux-android-4.9/prebuilt/darwin-x86_64/bin/aarch64-linux-android-readelf"
If it doesn't work, set empty value to readelf_path to force app_profiler.py pulling binaries each time.
readelf_path = ""

We have improved to find tools automatically in ndk r16, so it should be better.

**Comment by brok85** [comment]
Thanks a lot that fixed it.
