### ISSUE TITLE
dlopen failed: cannot locate symbol "_ZTVSt18basic_stringstreamIcSt11char_traitsIcESaIcEE"

### ISSUE THREAD

**Issue by thulioaraujo** [android-ndk/ndk#561]
#### Description

When I'm trying to execute my application this crash appears at runtime. It's been a while that I'm trying to solve this problem and searching some related problems on the internet but no success yet. Anyone can help me to figure out what is happening?

Here is the log:

`10-30 20:52:42.699 23502-23509/? E/art: Failed sending reply to debugger: Broken pipe
10-30 20:52:42.948 23502-23502/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: com.voxar.stam_ism.myapplication, PID: 23502
                                                   java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "_ZTVSt18basic_stringstreamIcSt11char_traitsIcESaIcEE" referenced by "/data/app/com.voxar.stam_ism.myapplication-1/lib/arm64/libnative-lib.so"...
                                                       at java.lang.Runtime.loadLibrary0(Runtime.java:989)
                                                       at java.lang.System.loadLibrary(System.java:1530)
                                                       at com.voxar.cslam.MainActivity.<clinit>(MainActivity.java:25)
                                                       at java.lang.Class.newInstance(Native Method)
                                                       at android.app.Instrumentation.newActivity(Instrumentation.java:1079)
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2557)
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726)
                                                       at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477)
                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at android.os.Looper.loop(Looper.java:159)
                                                       at android.app.ActivityThread.main(ActivityThread.java:6139)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
`

I've attached my gradle and CMakeList configuration file:

[CMakeLists.txt](https://github.com/android-ndk/ndk/files/1429166/CMakeLists.txt)
[gradle.txt](https://github.com/android-ndk/ndk/files/1429170/gradle.txt)

#### Environment Details

* NDK Version: r15c
* Build sytem: cmake
* Host OS: Windows
* Compiler: Clang
* ABI: 'x86', 'x86_64', 'armeabi', 'armeabi-', 'arm64-v8a'
* STL: c++_shared
* NDK API level: minSdkVersion 23, targetSdkVersion 26
* Device API level: 7.1.1

**Comment by DanAlbert** [comment]
That demangles to vtable for `std::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >`, which indicated that it's not libc++.

> STL: c++_shared

Looks like you're mixing STLs? You have a lot of `STATIC IMPORTED` libraries in your CMakeLists.txt. Presumably boost was built against gnustl and your app is built against libc++. You need to make sure you use the same STL across your entire application.

```cmake
add_library( ceres
             STATIC
             IMPORTED )
```

**Comment by DanAlbert** [comment]
Let me know if that's not the case and we're re-open, but that looks very likely.
