### ISSUE TITLE
Error linking sdclang with AOSP

### ISSUE THREAD

**Issue by fenilpaul** [android-ndk/ndk#598]
Hi, I am trying to build Oreo 8.01 for msm8909w processor, when compiling the following error occured.
 
```
$ make -j32
============================================
PLATFORM_VERSION_CODENAME=REL
PLATFORM_VERSION=8.1.0
TARGET_PRODUCT=msm8909go
TARGET_BUILD_VARIANT=userdebug
TARGET_BUILD_TYPE=release
TARGET_ARCH=arm
TARGET_ARCH_VARIANT=armv7-a-neon
TARGET_CPU_VARIANT=cortex-a7
HOST_ARCH=x86_64
HOST_2ND_ARCH=x86
HOST_OS=linux
HOST_OS_EXTRA=Linux-4.10.0-42-generic-x86_64-with-Ubuntu-16.04-xenial
HOST_CROSS_OS=windows
HOST_CROSS_ARCH=x86
HOST_CROSS_2ND_ARCH=x86_64
HOST_BUILD_TYPE=release
BUILD_ID=OPM1.171019.011
OUT_DIR=out
============================================
[44/44] bootstrap out/soong/.minibootstrap/build.ninja.in
[4/4] out/soong/.bootstrap/bin/minibp out/soong/.bootstrap/build.ninja
[865/866] glob vendor/qcom/opensource/interfaces/wifi/*/Android.bp
[39/54] test android/soong/cc/config
FAILED: out/soong/.bootstrap/soong-cc-config/test/test.passed 
out/soong/.bootstrap/bin/gotestrunner -p ./build/soong/cc/config -f out/soong/.bootstrap/soong-cc-config/test/test.passed -- out/soong/.bootstrap/soong-cc
config/test/test -test.short
panic: read /home/fenil/APQ8009W_LA.UM.6.7.r1-04400-8x09.0_N_v2.0.1: is a directory
goroutine 1 [running]:
android/soong/cc/config.setSdclangVars()
/home/fenil/APQ8009W_LA.UM.6.7.r1-04400-8x09.0_N_v2.0.1/build/soong/cc/config/global.go:206 +0x17bc
android/soong/cc/config.init.2()
/home/fenil/APQ8009W_LA.UM.6.7.r1-04400-8x09.0_N_v2.0.1/build/soong/cc/config/global.go:179 +0xcd6
android/soong/cc/config.init()
/home/fenil/APQ8009W_LA.UM.6.7.r1-04400-8x09.0_N_v2.0.1/build/soong/cc/config/tidy_test.go:42 +0x3cbb
main.init()
/home/fenil/APQ8009W_LA.UM.6.7.r1-04400-8x09.0_N_v2.0.1/out/soong/.bootstrap/soong-cc-config/test/test.go:64 +0x58
[41/54] compile out/soong/.bootstrap/soong-cc/test/android/soong/cc.a
ninja: build stopped: subcommand failed.
16:01:08 soong failed with: exit status 1
#### failed to build some targets (5 seconds) ####
```
 
I had downloaded the snapdragon-llvm-4.0.2-linux64.tar.gz and copied to prebuilts/clang/host/linux-x86/sdclang-4.0 and changed the device's BoardConfig.mk file. Still the error persists. How to solve this error?

**Comment by enh** [comment]
this is unrelated to the NDK.

**Comment by stephenhines** [comment]
Furthermore, I would strongly suggest that you not use closed-source toolchains that cannot be verified. Android's toolchains are produced using publicly available sources (you can repo init with "-b llvm-toolchain" in an AOSP repository to see/verify them). Without source availability + reproducible builds, there is no telling what the compiler is capable of (including misuse of your private source code and/or build machine).

**Comment by jinfeichao** [comment]
Hi,How to solve this error?
