### ISSUE TITLE
Prebuild shared libs not installed (to lib/arm)

### ISSUE THREAD

**Issue by Gibson85** [android-ndk/ndk#992]
Hi,

I am trying to get my app working for over a week now without success.
I have cross compiled multiple libs with clang for android and created a cmake ndk projekt in Android Studio where I want to link against these.
I placed the libs within the subfolder 'src/main/jniLibs' and if I use "Analyze APK" these are packed into the apk correctly.
But if I "Run" the application on my Phone (Android 7.1.2) I get an the following java exception:

```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.my.app, PID: 6603
    java.lang.UnsatisfiedLinkError: Unable to load native library "/data/app/com.my.app-1/lib/arm/libMyApp.so": dlopen failed: library "MyLibA.so" not found
        at android.app.NativeActivity.onCreate(NativeActivity.java:182)
        at android.app.Activity.performCreate(Activity.java:6684)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2637)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2751)
        at android.app.ActivityThread.-wrap12(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1496)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6186)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
```

This is my shortened "cmake" file:

```
cmake_minimum_required(VERSION 3.10.0)

add_library(native_app_glue STATIC ${ANDROID_NDK}/sources/android/native_app_glue/android_native_app_glue.c)
target_include_directories(native_app_glue PUBLIC ${ANDROID_NDK}/sources/android/native_app_glue)

find_library(log-lib log)

set(CMAKE_SHARED_LINKER_FLAGS "${CMAKE_SHARED_LINKER_FLAGS} -u ANativeActivity_onCreate")

...

add_library(libgperf SHARED IMPORTED)
add_library(MyLibA SHARED IMPORTED)
add_library(MyLibB SHARED IMPORTED)
add_library(MyLibC SHARED IMPORTED)
add_library(MyLibD SHARED IMPORTED)
add_library(MyLibE SHARED IMPORTED)

set_target_properties(libgperf PROPERTIES IMPORTED_LOCATION "${CMAKE_CURRENT_SOURCE_DIR}/src/main/jniLibs/${ANDROID_ABI}/libgperf.so")
set_target_properties(MyLibA PROPERTIES IMPORTED_LOCATION "${CMAKE_CURRENT_SOURCE_DIR}/src/main/jniLibs/${ANDROID_ABI}/MyLibA.so")
set_target_properties(MyLibB PROPERTIES IMPORTED_LOCATION "${CMAKE_CURRENT_SOURCE_DIR}/src/main/jniLibs/${ANDROID_ABI}/MyLibB.so")
set_target_properties(MyLibC PROPERTIES IMPORTED_LOCATION "${CMAKE_CURRENT_SOURCE_DIR}/src/main/jniLibs/${ANDROID_ABI}/MyLibC.so")
set_target_properties(MyLibD PROPERTIES IMPORTED_LOCATION "${CMAKE_CURRENT_SOURCE_DIR}/src/main/jniLibs/${ANDROID_ABI}/MyLibD.so")
set_target_properties(MyLibE PROPERTIES IMPORTED_LOCATION "${CMAKE_CURRENT_SOURCE_DIR}/src/main/jniLibs/${ANDROID_ABI}/MyLibE.so")

add_library(MyApp SHARED src/main/cpp/Main.cpp)

target_link_libraries(MyApp
        android
        native_app_glue
        ${log-lib}
		libgperf
		MyLibA
		MyLibB
		MyLibC
		MyLibD
		MyLibE
		EGL
		GLESv3)
```

That is my "build.gradle" file:

```
apply plugin: 'com.android.application'

apply plugin: 'kotlin-android'

apply plugin: 'kotlin-android-extensions'

android {
    compileSdkVersion 28
    defaultConfig {
        applicationId "com.my.app"
        minSdkVersion 18
        targetSdkVersion 28
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
        externalNativeBuild {
            cmake {
                arguments '-DANDROID_STL=c++_static'
            }
        }
        ndk {
            abiFilters 'armeabi-v7a'//, 'arm64-v8a', 'x86', 'x86_64'
        }
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    sourceSets {
        main {
            jniLibs.srcDirs = ['libs', 'src/main/jniLibs']
        }
    }
    externalNativeBuild {
        cmake {
            version '3.10.2'
            path file('CMakeLists.txt')
        }
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation"org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    implementation 'com.android.support:appcompat-v7:28.0.0'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.2'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'
}
```

Interestingly the static variants of my libs are compiling/executing well.
Also if I put the "libgperf.so" from the "hello-libs" example here on github into my app's "src/main/jniLibs" folder it becomes installed on the device correctly. But my "MyLibX.so" libs located also in this folder are not installed/ignored. I also checked that all my libs have the correct SONAME set.

The build command for the android studio project looks like:

```
Executable : /home/user/Android/Sdk/cmake/3.10.2.4988404/bin/cmake
arguments : 
-H/media/user/DRIVE/Programming/Android/MyApp/app
-B/media/user/DRIVE/Programming/Android/MyApp/app/.externalNativeBuild/cmake/debug/armeabi-v7a
-DANDROID_ABI=armeabi-v7a
-DANDROID_PLATFORM=android-18
-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/media/user/DRIVE/Programming/Android/MyApp/app/build/intermediates/cmake/debug/obj/armeabi-v7a
-DCMAKE_BUILD_TYPE=Debug
-DANDROID_NDK=/home/user/Android/Sdk/ndk-bundle
-DCMAKE_SYSTEM_NAME=Android
-DCMAKE_ANDROID_ARCH_ABI=armeabi-v7a
-DCMAKE_SYSTEM_VERSION=18
-DCMAKE_EXPORT_COMPILE_COMMANDS=ON
-DCMAKE_ANDROID_NDK=/home/user/Android/Sdk/ndk-bundle
-DCMAKE_TOOLCHAIN_FILE=/home/user/Android/Sdk/ndk-bundle/build/cmake/android.toolchain.cmake
-G Ninja
-DCMAKE_MAKE_PROGRAM=/home/user/Android/Sdk/cmake/3.10.2.4988404/bin/ninja
-DANDROID_STL=c++_static
```

Any ideas why my libs are ignored/not installed on the device (Android 7.1.2)?

**Comment by Gibson85** [comment]
One additional info. The final "libMyApp.so" doesn't depend on my prebuild libs at all. But the "libgperf.so" is marked as needed.

```
 0x00000001 (NEEDED)                     Shared library: [libandroid.so]
 0x00000001 (NEEDED)                     Shared library: [liblog.so]
 0x00000001 (NEEDED)                     Shared library: [libgperf.so]
 0x00000001 (NEEDED)                     Shared library: [libEGL.so]
 0x00000001 (NEEDED)                     Shared library: [libGLESv3.so]
 0x00000001 (NEEDED)                     Shared library: [libm.so]
 0x00000001 (NEEDED)                     Shared library: [libdl.so]
 0x00000001 (NEEDED)                     Shared library: [libc.so]
 0x0000000e (SONAME)                     Library soname: [libMyApp.so]
```

**Comment by alexcohn** [comment]
The file **MyLibA.so** is not installed on the device, because its name does not fit the pattern expected by package manager. Only files that follow the **lib**whatever**.so** pattern are copied from the APK to `/data/app/com.my.app-1/lib/arm`.

Consider renaming all the prebuilt libraries.

**Comment by alexcohn** [comment]
Don't expect this "fixed" any time soon, this has been the behaviour of both packager and installer since day one.

**Comment by DanAlbert** [comment]
Either way, it's not a behavior that's a part of the NDK, so I'd recommend filing a bug following b.android.com. If @alexcohn is right and this behavior is part of the platform and not just gradle, this is quite a bit more difficult to solve usefully since it can only be fixed for Android R+. It's definitely a part of the gradle plugin though, so we can start there.

**Comment by enh** [comment]
(he's right. this is part of the platform. it's so old that i don't know _why_ it's there. possibly so that they can more quickly reject non-library entries from the .zip file since they have to iterate over all the entries?)
